### ISSUE TITLE
Add the ability to accept an array as the second parameter in `RpcRouter` methods

### ISSUE THREAD

**Issue by gomzyakov** [avto-dev/json-rpc-laravel#14]
Now `RpcRouter` allows you to pass only a string as the second parameter:

```php
use AvtoDev\JsonRPC\RpcRouter;

RpcRouter::on('please_sum_array_values', 'SomeController@sum');
RpcRouter::on('show_full_request', 'SomeController@showInfo');
```

The original Laravel [router](https://laravel.com/docs/9.x/routing) can also take an array as the second parameter.

Please add the ability to accept an array as the second parameter in `RpcRouter` methods, like:

```php
use AvtoDev\JsonRPC\RpcRouter;

RpcRouter::on('please_sum_array_values', [SomeController::class, 'sum']);
RpcRouter::on('show_full_request', [SomeController::class, 'showInfo']);
```

**Comment by shirokovnv** [comment]
@gomzyakov Is issue still actual ? If so, I can help with making a PR.

**Comment by gomzyakov** [comment]
@shirokovnv 


No one has had a need for the feature mentioned in almost 2 years. I think the issue can be closed)
