### ISSUE TITLE
Can I protect my RpcRouter routes with Sanctum

### ISSUE THREAD

**Issue by kkalchev** [avto-dev/json-rpc-laravel#9]
package: avto-dev/json-rpc-laravel

Can I use a Laravel middleware (Sanctum guard) to protect my RpcRouter routes or how can I use Sanctum with this RPC Router to protect my methods?
I need something like that:

// routes/api.php
Route::post('/rpc', \AvtoDev\JsonRpc\Http\Controllers\RpcController::class);

// Not protected routes:
RpcRouter::on('login', AuthController::class."@login");
...

// Protected routes:
Route::middleware(['auth:sanctum'])->group(function () {
    RpcRouter::on('show_full_request', AuthController::class."@showInfo");
    ...
});

**Comment by eldario** [comment]
Hello, @kkalchev !

There is no **such** possibility out of the box.

You create one endpoint called `/rpc` and `middleware` works only for it.

There are 3 options:
1. Hang one middleware on `/rpc` and implement the rules inside it (That is, set a label, cookies and, for example, use a `trait` to do authentication checks)
2. Create a new `/rpc_auth` and close it with `middleware`
3. Create a `PR` for this repository with your changes

**Comment by eldario** [comment]
@kkalchev 
Did I help you in solving the issue?
